# Sku Generation on SQLite DB

In [1]:
#import necessary libraries
import os
import sys
import time
import pandas as pd
import sqlalchemy
import sqlite3

In [2]:
# connect to the database
conn = sqlite3.connect('sku_catalog.db')

In [3]:
# preview product list
query = "SELECT * FROM products LIMIT 10"
df_preview = pd.read_sql_query(query, conn)
df_preview

,id,product_name,category_id,description,base_price,status,created_at,updated_at
0,1,Bandit Banquet Tee,1,Raise a cold one to automotive history with th...,20,active,2025-12-02 20:47:57.632166,2025-12-02 20:47:57.632170
1,2,Bandit Truck Wreath Tee,1,Embrace the spirit of Legendary with our Bandi...,20,active,2025-12-02 20:47:57.635340,2025-12-02 20:47:57.635344
2,3,Bandit Truck Logo Tee,1,"Show your passion for powerful, custom muscle ...",20,active,2025-12-02 20:47:57.639244,2025-12-02 20:47:57.639246
3,4,Legendary Tee,1,Experience the pride of driving Legendary with...,20,active,2025-12-02 20:47:57.642034,2025-12-02 20:47:57.642037
4,5,Legendary Long Sleeve Tee,2,Experience the epitome of style and protection...,20,active,2025-12-02 20:47:57.644838,2025-12-02 20:47:57.644841
5,6,Legendary Polo,3,"Elevate your style with the Legendary Polo, a ...",40,active,2025-12-02 20:47:57.646922,2025-12-02 20:47:57.646924
6,7,Legendary Sweater,4,Wrap yourself in the power of Legendary Concep...,22,active,2025-12-02 20:47:57.648896,2025-12-02 20:47:57.648898
7,8,Bandit Truck Wreath Sweater,4,Introducing the Bandit Wreath Sweater – a bold...,22,active,2025-12-02 20:47:57.650957,2025-12-02 20:47:57.650959
8,9,Legendary Hoody,5,Unleash your inner muscle truck enthusiast wit...,25,active,2025-12-02 20:47:57.653287,2025-12-02 20:47:57.653289
9,10,Bandit Truck Jacket,6,"Introducing the Bandit Truck Jacket, a must-ha...",65,active,2025-12-02 20:47:57.655177,2025-12-02 20:47:57.655179

In [4]:
# preview a single product and its features
product_id = 1
query = f"""SELECT 
    p.product_name,
    c.category,
    c.subcategory,
    ft.feature_type,
    f.name AS feature_name,
    f.code AS feature_code
FROM products p
JOIN categories c ON p.category_id = c.id
JOIN product_features pf ON p.id = pf.product_id
JOIN features f ON pf.feature_id = f.id
JOIN feature_types ft ON f.feature_type_id = ft.id
WHERE p.product_name = 'Bandit Truck Logo Tee'
ORDER BY ft.display_order, f.sort_order;"""
df_product = pd.read_sql_query(query, conn)
df_product

,product_name,category,subcategory,feature_type,feature_name,feature_code
0,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Youth Small,YS
1,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Youth Medium,YM
2,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Youth Large,YL
3,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Extra Small,XS
4,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Small,S
5,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Medium,M
6,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Large,L
7,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Extra Large,XL
8,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Double Extra Large,2XL
9,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Triple Extra Large,3XL
10,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Quadruple Extra Large,4XL
11,Bandit Truck Logo Tee,Shirt,Tee Shirt,Size,Quintuple Extra Large,5XL
12,Bandit Truck Logo Tee,Shirt,Tee Shirt,Fit,Unisex,USX
13,Bandit Truck Logo Tee,Shirt,Tee Shirt,Color,Black,BLK
14,Bandit Truck Logo Tee,Shirt,Tee Shirt,Design,Bandit Truck Icon,BTI
15,Bandit Truck Logo Tee,Shirt,Tee Shirt,Design,Bandit Truck Wordmark,BTW
16,Bandit Truck Logo Tee,Shirt,Tee Shirt,Material,Cotton,CTN
17,Bandit Truck Logo Tee,Shirt,Tee Shirt,Scent,Not Applicable,STNAN

# Permutations on a single product

In [19]:
# function for, given a single product, generate all possible perutations of its features
def generate_permutations(product_name, debug=False):
    
    def combine_design_codes(design_codes):
        """
        Combine icon (I) and wordmark (W) design codes into logo (L) codes.
        BTI + BTW = BTL
        LGI + LGW = LGL
        If 3+ codes, find matching pairs and discard odd ones.
        """
        if not design_codes or len(design_codes) < 2:
            return design_codes
        
        # Look for matching pairs (same first 2 letters, one ends in I, one in W)
        combined = []
        used = set()
        
        for i, code1 in enumerate(design_codes):
            if i in used or len(code1) < 3:
                continue
            
            # Check if this ends with 'I'
            if code1[-1] == 'I':
                # Look for matching 'W' variant
                prefix = code1[:-1]  # e.g., "BT" from "BTI"
                w_code = prefix + 'W'
                
                if w_code in design_codes:
                    # Found a pair! Combine to L
                    logo_code = prefix + 'L'
                    combined.append(logo_code)
                    used.add(i)
                    used.add(design_codes.index(w_code))
                elif code1 not in used:
                    # No pair, keep original
                    combined.append(code1)
                    used.add(i)
            elif i not in used:
                # Not part of a pair, keep it
                combined.append(code1)
                used.add(i)
        
        return combined
    
    query = f"""SELECT 
        p.product_name,
        c.category,
        c.subcategory,
        c.prefix as category_prefix,
        ft.feature_type,
        f.name AS feature_name,
        f.code AS feature_code
    FROM products p
    JOIN categories c ON p.category_id = c.id
    JOIN product_features pf ON p.id = pf.product_id
    JOIN features f ON pf.feature_id = f.id
    JOIN feature_types ft ON f.feature_type_id = ft.id
    WHERE p.product_name = '{product_name}'
    ORDER BY ft.display_order, f.sort_order;"""
    
    df_product = pd.read_sql_query(query, conn)
    
    # Get the category prefix (same for all rows)
    category_prefix = df_product['category_prefix'].iloc[0] if len(df_product) > 0 else None
    
    if debug:
        print(f"\nQuery returned {len(df_product)} rows")
        if len(df_product) == 0:
            print("WARNING: No data returned from query!")
            return []
    
    # Group features by feature type
    feature_groups = df_product.groupby('feature_type')['feature_code'].apply(list).to_dict()
    
    # Extract Design features separately (don't permutate them)
    design_codes = feature_groups.pop('Design', [])

    # debug print values
    if debug:
        print(f"\nDesign features (product-level): {design_codes}")
        print(f"\n{len(feature_groups)} feature groups before culling:")
        for key in feature_groups:
            print(f"  Feature Type: {key}, Features: {feature_groups[key]}")

    # cull NAN values from feature groups (check if last 3 characters are 'NAN')
    for key in feature_groups:
        feature_groups[key] = [code for code in feature_groups[key] if pd.notna(code) and not str(code).endswith('NAN')]
    
    # Also cull NAN from design codes
    design_codes = [code for code in design_codes if pd.notna(code) and not str(code).endswith('NAN')]
    
    # Combine icon + wordmark pairs into logo codes
    design_codes = combine_design_codes(design_codes)
    
    if debug and design_codes:
        print(f"Design codes after combining I+W pairs: {design_codes}")
    
    # Remove empty feature groups
    feature_groups = {k: v for k, v in feature_groups.items() if v}
    
    if debug:
        print(f"\n{len(feature_groups)} feature groups after culling:")
        for key in feature_groups:
            print(f"  Feature Type: {key}, Features: {feature_groups[key]}")
    
    if not feature_groups:
        print("WARNING: No valid feature groups found after culling!")
        return []

    # Store the feature type names in order for later reference
    feature_type_order = list(feature_groups.keys())

    # Generate all combinations of features
    from itertools import product
    permutations = [list(combo) for combo in product(*feature_groups.values())]

    # check for duplicates (convert lists to tuples for set comparison)
    unique_permutations = set(tuple(p) for p in permutations)
    if len(unique_permutations) < len(permutations):
        print("Warning: Duplicate permutations found!")
    if debug:
        print(f"\nTotal permutations generated: {len(permutations)}")
        print(f"Unique permutations count: {len(unique_permutations)}")

    if debug:
        # Print first few permutations as preview
        print(f"\nCategory prefix: {category_prefix}")
        print(f"Design codes: {design_codes}")
        print(f"Feature types order: {feature_type_order}")
        print(f"\nSample permutations (first 5):")
        for i, perm in enumerate(permutations[:5], 1):
            print(f"  {i}. ('{product_name}', '{category_prefix}', {design_codes}, {feature_type_order}, {perm})")
        if len(permutations) > 5:
            print(f"  ... and {len(permutations) - 5} more")
    
    # Return list of tuples: (product_name, category_prefix, design_codes, feature_type_order, feature_codes)
    return [(product_name, category_prefix, design_codes, feature_type_order, perm) for perm in permutations]

# test the function
test_permutations = generate_permutations('Bandit Truck Logo Tee',True)

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

In [7]:
test_permutations[:3]  # preview first 3 permutations

[('Bandit Truck Logo Tee',
  'SH-TESH',
  ['BTI', 'BTW'],
  ['BLK', 'USX', 'CTN', 'YS']),
 ('Bandit Truck Logo Tee',
  'SH-TESH',
  ['BTI', 'BTW'],
  ['BLK', 'USX', 'CTN', 'YM']),
 ('Bandit Truck Logo Tee',
  'SH-TESH',
  ['BTI', 'BTW'],
  ['BLK', 'USX', 'CTN', 'YL'])]

# Generate SKUs from product permutations

In [20]:
from typing import List, Tuple
import base36

# function to generate a SKU from a permutation tuple (product_name, category_prefix, design_codes, feature_type_order, feature_codes)

def generate_sku(permutation: Tuple[str, str, List[str], List[str], List[str]], add_timestamp=False, debug=True):
    product_name, category_prefix, design_codes, feature_type_order, feature_codes = permutation
    
    if debug:
        print(f"Product: {product_name}")
        print(f"Category Prefix: {category_prefix}")
        print(f"Design Codes: {design_codes}")
        print(f"Feature Codes: {feature_codes}")
    
    # Build SKU: category_prefix + design_codes + feature_codes
    sku_parts = [category_prefix]
    
    # Add design codes (if any)
    if design_codes:
        sku_parts.extend(design_codes)
    
    # Add feature codes
    sku_parts.extend(feature_codes)
    
    # Add compressed timestamp if requested
    if add_timestamp:
        import time
        timestamp = int(time.time())
        compressed_time = base36.dumps(timestamp).upper()
        sku_parts.append(compressed_time)
        if debug:
            print(f"Added timestamp: {timestamp} → {compressed_time}")
    
    # Join with dashes
    sku = "-".join(sku_parts)

    if debug:
        print(f"Generated SKU: {sku}\n # of characters: {len(sku)}")

    return sku

# test the function
test_sku = generate_sku(test_permutations[0], debug=True)
print("----------------------------------------------------")
test_sku_with_timestamp = generate_sku(test_permutations[0], add_timestamp=True, debug=True)

Product: Bandit Truck Logo Tee
Category Prefix: SH-TESH
Design Codes: ['BTL']
Feature Codes: ['BLK', 'USX', 'CTN', 'YS']
Generated SKU: SH-TESH-BTL-BLK-USX-CTN-YS
 # of characters: 26
----------------------------------------------------
Product: Bandit Truck Logo Tee
Category Prefix: SH-TESH
Design Codes: ['BTL']
Feature Codes: ['BLK', 'USX', 'CTN', 'YS']
Added timestamp: 1765813726 → T7BILA
Generated SKU: SH-TESH-BTL-BLK-USX-CTN-YS-T7BILA
 # of characters: 33

### Check for Duplicate SKUs

In [15]:
def validate_sku(sku: str, product_name: str, debug=False):
    """
    Validate SKU:
    1. Must be 40 characters or less
    2. Cannot exist for a different product (same product is OK)
    
    Returns: (is_valid, warnings)
    """
    warnings = []
    
    # Check length
    if len(sku) > 40:
        warnings.append(f"SKU too long: {len(sku)} characters (max 40)")
    
    # Check for duplicate SKU in different product
    query = f"""SELECT p.product_name 
        FROM skus s
        JOIN products p ON s.product_id = p.id
        WHERE s.sku = '{sku}';"""
    
    df_existing = pd.read_sql_query(query, conn)
    
    if len(df_existing) > 0:
        existing_product = df_existing['product_name'].iloc[0]
        if existing_product != product_name:
            warnings.append(f"SKU '{sku}' already exists for different product: '{existing_product}'")
        elif debug:
            print(f"SKU '{sku}' already exists for same product '{product_name}' - OK")
    
    is_valid = len(warnings) == 0
    
    if debug and warnings:
        print(f"Validation failed for SKU '{sku}':")
        for warning in warnings:
            print(f"  - {warning}")

    elif debug:
        print(f"SKU '{sku}' is valid.")
    
    return is_valid, warnings

# test the function
is_valid, warnings = validate_sku(test_sku, 'Bandit Truck Logo Tee', True)

SKU 'SH-TESH-BTL-BLK-USX-CTN-YS' is valid.

In [ ]:
def generate_product_skus_df(product_name, add_timestamp=False, debug=False):
    """
    Generate all SKU permutations for a product and return as DataFrame.
    
    Returns DataFrame with columns:
    - product_name
    - category_prefix
    - design_codes (as string)
    - [individual feature type columns]
    - sku
    """
    # Generate all permutations
    permutations = generate_permutations(product_name, debug=debug)
    
    if not permutations:
        print(f"No permutations generated for '{product_name}'")
        return pd.DataFrame()
    
    # Get feature type order from first permutation
    _, _, _, feature_type_order, _ = permutations[0]
    
    # Build DataFrame rows
    rows = []
    for perm in permutations:
        product_name, category_prefix, design_codes, feature_types, feature_codes = perm
        
        # Generate SKU
        sku = generate_sku(perm, add_timestamp=add_timestamp, debug=False)
        
        # Build row dict
        row = {
            'product_name': product_name,
            'category_prefix': category_prefix,
            'design_codes': '-'.join(design_codes) if design_codes else '',
        }
        
        # Add individual feature columns
        for i, feature_type in enumerate(feature_types):
            row[feature_type] = feature_codes[i]
        
        # Add SKU column
        row['sku'] = sku
        
        rows.append(row)
    
    df = pd.DataFrame(rows)
    
    if debug:
        print(f"\nGenerated {len(df)} SKUs for '{product_name}'")
        print(f"Sample SKUs:\n{df.head()}")
    
    return df

# Test the function
test_df = generate_product_skus_df('Bandit Truck Logo Tee', debug=True)
test_df.head(10)

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']

Total permutations generated: 12
Unique permutations count: 12

Category prefix: SH-TESH
Design codes: ['BTL']
Feature types order: ['Color', 'Fit', 'Material', 'Size']

Sample permutations (first 5):
  1. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YS'])
  2. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YM'])
  3. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'YL'])
  4. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'XS'])
  5. ('Bandit Truck Logo Tee', 'SH-TESH', ['BTL'], ['Color', 'Fit', 'Material', 'Size'], ['BLK', 'USX', 'CTN', 'S'])
  ... and 7 more

Query returned 18 rows

Design features (product-level): ['BTI', 'BTW']

5 feature groups before culling:
  Feature Type: Color, Features: ['BLK']
  Feature Type: Fit, Features: ['USX']
  Feature Type: Material, Features: ['CTN']
  Feature Type: Scent, Features: ['STNAN']
  Feature Type: Size, Features: ['YS', 'YM', 'YL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL']
Design codes after combining I+W pairs: ['BTL']

4 feature groups after culling:
  Feature Type: Color, Features: ['BLK']

RecursionError: maximum recursion depth exceeded

## Generate Category Prefix
In lieu of mannually writing catogry prefixes, and to prevent duplicates. I'm writing a function that finds categories (main and sub) with missing prefixes (a field in the categories table) and procedurally generates them. This improves scalability as future categories are added to the catalog.

In [8]:
def generate_missing_category_prefixes(debug=False):
    """
    Generate prefixes for categories based on the algorithm:
    - Get first two letters of each word in main category
    - Get first two letters of first two words in subcategory
    - Join letters with a dash
    """

    def find_missing_category_prefixes():
        """
        Function to find categories with missing or invalid prefixes.
        Returns a DataFrame of such categories.
        """
        # check for missing prefixes in the categories table
        query = """SELECT 
            id,
            category,
            subcategory
        FROM categories
        WHERE prefix IS NULL OR prefix = '' OR prefix NOT GLOB '[0-9]*';"""
        df_missing_prefixes = pd.read_sql_query(query, conn)
        return df_missing_prefixes

    df_categories = find_missing_category_prefixes()
    print(f"Found {len(df_categories)} categories with missing or invalid prefixes.")

    for index, row in df_categories.iterrows():
        category_id = row['id']
        category = row['category']
        subcategory = row['subcategory']

        # Generate prefix
        category_parts = category.split()
        subcategory_parts = subcategory.split()[0:2]  # first two words only

        prefix_parts = []
        subcat_prefix = ""
        for part in category_parts:
            prefix_parts.append(part[:2].upper())
        for part in subcategory_parts:
            subcat_prefix += part[:2].upper()
        prefix_parts.append(subcat_prefix)
            
        prefix = "-".join(prefix_parts)

        # add prefix to df_categories for reference
        df_categories.at[index, 'generated_prefix'] = prefix

    if debug:
        print(f"Category ID: {category_id}, Category: '{category}', Subcategory: '{subcategory}', Generated Prefix: '{prefix}'")
    else:
        print(f"Category ID: {category_id}, Generated Prefix: '{prefix}'")
        # Update the database with the new prefix
        update_query = f"""UPDATE categories
            SET prefix = '{prefix}'
            WHERE id = {category_id};"""
        conn.execute(update_query)
        conn.commit()
    
    return df_categories

df_missing_prefixes = generate_missing_category_prefixes(True)
df_missing_prefixes

Found 11 categories with missing or invalid prefixes.
Category ID: 11, Category: 'Accessories', Subcategory: 'Keychain', Generated Prefix: 'AC-KE'

    id     category            subcategory generated_prefix
0    1        Shirt              Tee Shirt          SH-TESH
1    2        Shirt  Long Sleeve Tee Shirt          SH-LOSL
2    3        Shirt                   Polo            SH-PO
3    4    Outerwear                Sweater            OU-SW
4    5    Outerwear                  Hoody            OU-HO
5    6    Outerwear                 Jacket            OU-JA
6    7     Headwear            Trucker Hat          HE-TRHA
7    8     Headwear               Ball Cap          HE-BACA
8    9     Headwear           Flex Fit Hat          HE-FLFI
9   10  Accessories          Air Freshener          AC-AIFR
10  11  Accessories               Keychain            AC-KE

In [36]:
# df_missing_prefixes = generate_missing_category_prefixes()

Found 11 categories with missing or invalid prefixes.
Category ID: 11, Generated Prefix: 'AC-KE'

### Current issues 12/08/25
Certain features are still not pulling prefixes/code such as design. I think it's a database relations issue and not a code issue

### Current issues 12/09/25
Design feature was infact missing a lot relations, some existing ones were incorrect. This has all been resolved on the DB itself. 
To generate SKUs. The strategy should be:
- Permutate on features unique to each product variant (eg. size)
- Sku gen with other features (eg Design) that have multiple values but are consistent accross all variants